### ISSUE TITLE
Rights management when linking to Gdocs and Gsheets

### ISSUE THREAD

**Issue by StroemPhi** [nfdi-de/section-metadata-wg-onto#1]
Currently, we have the problem that the Section folks changed in the rights management of our GDrive folder. Hence, I changed a lot of our common documents to be editable by everyone. This is not good when we want to link to these files within this repo. To be able to do the latter, I'd need a list of all WG members' emails that they use to work within Gdocs/slides, so I can adjust the rights to allow edits only by our members.

**Comment by ustervbo** [comment]
My impression of Google is that you can assign rights to a Google Group, so that everyone who is registered in the group has the same rights on the document or sheet that the group is added to.

Would that solve the problem?

**Comment by StroemPhi** [comment]
No Google Group made, but instead granted access to all who subscribed to our WG mailing list.
